kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-filadapter
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "7ef907b4-ec9f-47dd-ab41-4e54ba32ceb1" #AAD pensjonopptjening testgruppe
  webproxy: true
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-fss
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q2
    - name: FILSLUSE_HOST
      value: filmottak.preprod.local
    - name: FILSLUSE_PORT
      value: "22"
    - name: FILSLUSE_USERNAME
      value: srvPopp
  envFrom:
    - secret: unleash-api-token
    - secret: filadapter-sshkey
  image: {{ image }}
  ingresses:
    - "https://pensjon-opptjening-filadapter.intern.dev.nav.no"
    - "https://pensjon-opptjening-filadapter.dev.adeo.no"
    - "https://pensjon-opptjening-filadapter.intern.dev.adeo.no"
    - "https://pensjon-opptjening-filadapter.nais.preprod.local"
    - "https://pensjon-opptjening-filadapter.dev-fss-pub.nais.io"

  accessPolicy:
    outbound:
      external:
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: filmottak.preprod.local
          ports:
            - port: 22
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: pensjon-opptjening-admin-web
          namespace: pensjonopptjening
          cluster: dev-gcp
          permissions:
            roles:
              - fil.lagre
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    port: "8080"
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "2"
      memory: 9192Mi
    requests:
      cpu: 500m
      memory: 2048Mi
