apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: pensjon-opptjening-filadapter
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: pensjonopptjening
  secretName: unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: development