name: 'Bygg branch'

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Setup Java'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'gradle'

      - name: 'Build and test'
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload test results'
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: failed-test-results
          path: build/reports/tests/test
