name: Monitor dependencies with Dependabot
on:
  schedule:
    - cron: '25 8,13 * * 1,2,3,4,5'
    - cron: '25 13 * * 0,6'
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
      - "gradle.properties"
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.1.1
      - name: 'Java 21'
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Run snapshot action for compileClasspath
        uses: mikepenz/gradle-dependency-submission@v1
        with:
          gradle-build-configuration: "compileClasspath"
      - name: Run snapshot action for runtimeClasspath
        uses: mikepenz/gradle-dependency-submission@v1
        with:
          gradle-build-configuration: "runtimeClasspath"
      - name: Run snapshot action for testCompileClasspath
        uses: mikepenz/gradle-dependency-submission@v1
        with:
          gradle-build-configuration: "testCompileClasspath"
      - name: Run snapshot action for testRuntimeClasspath
        uses: mikepenz/gradle-dependency-submission@v1
        with:
          gradle-build-configuration: "testRuntimeClasspath"